version: "3.4"
services:
  ayro-webcm:
    image: "ayro-webcm:latest"
    container_name: "ayro-webcm"
    hostname: "ayro-webcm"
    network_mode: "host"
    volumes:
      - "./config.properties:/usr/src/ayro-webcm/config.properties"